apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh-mock.fullname" . }}
  labels:
    {{- include "ssh-mock.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "ssh-mock.selectorLabels" . | nindent 4 }}
